# Generated by Django 5.0.6 on 2024-06-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_helprequest_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helprequest',
            old_name='creator_name',
            new_name='Prénom',
        ),
        migrations.RenameField(
            model_name='helprequest',
            old_name='subject_name',
            new_name='Thème',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='subject_field',
        ),
        migrations.AddField(
            model_name='helprequest',
            name='Branche',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
