# Generated by Django 5.0.6 on 2024-06-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_rename_creator_name_helprequest_prénom_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='helprequest',
            old_name='question',
            new_name='Question',
        ),
    ]
