# Generated by Django 5.0.6 on 2024-06-08 10:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_rename_question_helprequest_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branche', models.CharField(max_length=100)),
                ('thème', models.CharField(max_length=200)),
                ('prénom', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='response',
            name='help_request',
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prénom', models.CharField(max_length=100)),
                ('réponse_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='src.question')),
            ],
        ),
        migrations.DeleteModel(
            name='HelpRequest',
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
