# Generated by Django 5.0.6 on 2024-06-08 17:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0005_question_remove_response_help_request_reponse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='prénom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='thème',
            new_name='theme',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('answer_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='src.question')),
            ],
        ),
        migrations.DeleteModel(
            name='Reponse',
        ),
    ]
